.TH FASTBASE64 1 "March 2026" "simdutf" "User Commands"
.SH NAME
fastbase64 \- base64 encode/decode data and print to standard output
.SH SYNOPSIS
.B fastbase64
[\fB\-Ddh\fR] [\fB\-b\fR \fInum\fR] [\fB\-i\fR \fIin_file\fR] [\fB\-o\fR \fIout_file\fR]
.SH DESCRIPTION
.B fastbase64
encodes or decodes base64 data using the high-performance simdutf library.
By default, it encodes binary input to base64 output. On large files,
it can be several times faster than standard base64 tools.
If a second filename is provided, it is used as the output file.
Otherwise, output goes to standard output.
.SH OPTIONS
.TP
.B \-b, \-\-break \fInum\fR
break encoded output up into lines of length \fInum\fR (default 0, meaning no breaks)
.TP
.B \-D, \-d, \-\-decode
decode input
.TP
.B \-h, \-\-help
display this message
.TP
.B \-i, \-\-input \fIin_file\fR
input file (default: "-" for stdin)
.TP
.B \-o, \-\-output \fIout_file\fR
output file (default: "-" for stdout)
.TP
.B \-w, \-\-wrap=\fINUM\fR
same as \fB\-b\fR
.TP
.B \-e, \-\-encode
encode input (default)
.TP
.B \-\-ignore\-garbage
when decoding, ignore non-alphabet characters
.TP
.B \-\-version
output version information and exit
.SH EXAMPLES
.TP
Encode a file (default, no wrapping):
.B fastbase64 \-i myfile.txt
.TP
Decode base64 data:
.B fastbase64 \-d \-i encoded.txt
.TP
Encode with custom line wrapping:
.B fastbase64 \-b 76 \-i myfile.txt
.SH SEE ALSO
.BR base64 (1),
.BR iconv (1)
.SH AUTHOR
Written by the simdutf development team.