/*
 * Lookup-table generator for utf8_to_utf16le_neon.S.
 *
 * This table is indexed by the Tetranacci numbers, and holds 8-byte entries
 * containing information about the transcoding of a 16-byte chunk of input.
 * The index is as follows: the input bytes are classified.  Those that are
 * FOLLOW bytes (0x80--0xBF) select the entry at the corresponding index of
 * sequence
 *
 *     0, 1, 2, 4, 8, 15, 29, 56, 108, 208, 401, 773, 1490, 2872, 5536, 10671
 *
 * (OEIS A000078 with the first element cleared) and the table index is the
 * sum of the selected indices, for 20569 entries in total.  This scheme
 * indexes all valid UTF-8 inputs, i.e. those that have no more than three
 * consecutive FOLLOW bytes and that start with a LEAD byte.  We'll have to
 * validate that this is the case separately.
 *
 * Each table entry is eight bytes, the bits hold the following information:
 *
 *     0x80 -- if clear, a sequence is decoded into this slot
 *     0x40 -- the sequence is part of a four byte sequence
 *     0x20 -- the sequence has three bytes
 *     0x10 -- the sequence has two bytes
 *     0x0f -- index of the last byte in the sequence decoded for this slot
 *
 * This gives the following six cases:
 *
 *     0x0* -- ASCII
 *     0x1* -- 2BYTE two-byte sequence
 *     0x2* -- 3BYTE three-byte sequence
 *     0x5* -- 4TAIL last two bytes of a four-byte sequence
 *     0x6* -- 4HEAD first three bytes of a four-byte sequence
 *     0xf* -- EMPTY empty slot
 *
 * Up to eight sequences are decoded.  If less sequences are decoded, the
 * remaining slots are filled with 0xff, except for the final slot, which
 * holds the negated number of sequences encoded.  Four byte sequences
 * are decoded into two slots, holding the index of the final and penultimate
 * byte of the sequence respectively.
 *
 * Here is a sample table entry: for input vector
 *
 *     40 C2 A7 E2 88 88 F0 9D 92 AA E2 89 A4 C2 B1 31
 *
 * we get FOLLOW syndrome
 *
 *     00 00 FF 00 FF FF 00 FF FF FF 00 FF FF 00 FF 00
 *
 * and hence Tetranacci index
 *
 *     3 + 8 + 15 + 56 + 108 + 208 + 774 + 1490 + 5536 = 8198
 *
 * at which we find entry
 *
 *     00 12 25 68 59 2C 1E 0F
 *
 * representing:
 *
 *     00: 1-byte sequence ending at index 0 (40)
 *     12: 2-byte sequence ending at index 2 (C2 A7)
 *     25: 3-byte sequence ending at index 5 (E2 88 88)
 *     68: first half of 4-byte sequence ending at index 8 (F0 9D 92)
 *     59: second half of 4-byte sequence ending at index 9 (92 AA)
 *     2C: 3-byte sequence ending at index 12 (E2 89 A4)
 *     1E: 2-byte sequence ending at index 14 (C2 B1)
 *     0F: 1-byte sequence ending at index 15 (31)
 */

#include <assert.h>
#include <stdalign.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

enum { TABLEN = 20569 };

alignas(8) unsigned char utf8_to_utf16le_neon_tab[TABLEN][8];

static void
gentab(void)
{
	long m, i;

	memset(utf8_to_utf16le_neon_tab, 0xff, sizeof utf8_to_utf16le_neon_tab);

	for (m = i = 0; m <= 0xffff; m += 2) {
		int j, k, start;

		/* four or more consecutive bits set in m? */
		if (m & m >> 1 & m >> 2 & m >> 3)
			continue;

		j = 0; /* index into utf8_to_utf16le_neon_tab[i] */
		start = 0; /* start of current sequence */

		/* iterate over bits of m, skipping the first bit */
		for (k = 1; k < 16; k++) {
			/* follow byte? */
			if (m & 1 << k)
				continue;

			/* else first byte of next sequence */
			switch (k - start) {
			case 1:	utf8_to_utf16le_neon_tab[i][j++] = k - 1;
				break;

			case 2:	utf8_to_utf16le_neon_tab[i][j++] = k - 1 | 0x10;
				break;

			case 3:	utf8_to_utf16le_neon_tab[i][j++] = k - 1 | 0x20;
				break;

			case 4:	if (j >= 7)
					goto done;

				utf8_to_utf16le_neon_tab[i][j++] = k - 2 | 0x60;
				utf8_to_utf16le_neon_tab[i][j++] = k - 1 | 0x50;
				break;

			default:
				assert(k - start <= 4);
			}

			start = k;

			if (j >= 8)
				goto done;
		}

		/*
		 * Special case: if a four byte sequence starts at index 12 and we
		 * have space for it, put it in.
		 */
		if (start == 12 && j < 7) {
			utf8_to_utf16le_neon_tab[i][j++] = (k - 2) | 0x60;
			utf8_to_utf16le_neon_tab[i][j++] = (k - 1) | 0x50;
		}

		/* go to next table row */
	done:	if (j <= 7)
			utf8_to_utf16le_neon_tab[i][7] = -j;

		i++;	
	}

	assert(i == TABLEN);
}

int main()
{
	long i, j, m;

	gentab();

	printf("/* --- GENERATED BY mktab_neon.c DO NOT EDIT --- */\n\n"
	    "#include <stdalign.h>\n\n"
	    "alignas(8) unsigned const char utf8_to_utf16le_neon_tab[%d][8] = {\n",
	    TABLEN);

	for (m = i = 0; m <= 0xffff; m += 2) {
		int j, k;

		/* four or more consecutive bits set in m? */
		if (m & m >> 1 & m >> 2 & m >> 3)
			continue;

		fputs("\t{", stdout);

		for (j = 0; j < 8; j++)
			printf(" 0x%02x,", (unsigned)utf8_to_utf16le_neon_tab[i][j]);

		printf(" }, /* 0x%04x */\n", (unsigned)m);
		i++;
	}

	puts("};");

	assert(i == TABLEN);

	if (ferror(stdout)) {
		perror("stdout");

		return (EXIT_FAILURE);
	}

	return (EXIT_SUCCESS);
}
