/*
 * Lookup-table generator for utf8_to_utf16le_neon.S.
 *
 * The tables are indexed by the Tetranacci numbers, and hold 8-byte entries
 * containing information about the transcoding of 8-byte chunks of input.
 * The index is as follows: the input bytes are classified.  Those that are
 * FOLLOW bytes (0x80--0xBF) select the entry at the corresponding index of
 * sequence
 *
 *     1, 2, 4, 8, 15, 29, 56, 108
 *
 * (OEIS A000078) and the table index is the sum of the selected indices,
 * for 208 entries in total.  Then, one table is selected based on how many
 * consecutive bytes after these 8 bytes are FOLLOW bytes, giving 4 distinct
 * tables.  The scheme indexes all valid UTF-8 inputs, i.e. those that have
 * no more than three consecutive FOLLOW bytes and that start with a LEAD
 * byte.  We'll have to validate that this is the case separately.
 *
 * Each table entry is eight bytes, the bits hold the following information:
 *
 *     0x80 -- if clear, a sequence is decoded into this slot
 *     0x40 -- the sequence is part of a four byte sequence
 *     0x20 -- the sequence has three bytes
 *     0x10 -- the sequence has two bytes
 *     0x0f -- index of the last byte in the sequence decoded for this slot
 *
 * This gives the following six cases:
 *
 *     0x0* -- ASCII
 *     0x1* -- 2BYTE two-byte sequence
 *     0x2* -- 3BYTE three-byte sequence
 *     0x5* -- 4TAIL last two bytes of a four-byte sequence
 *     0x6* -- 4HEAD first three bytes of a four-byte sequence
 *     0xf* -- EMPTY empty slot
 *
 * Up to eight sequences are decoded.  If less sequences are decoded, the
 * remaining slots are filled with 0xff, except for the final slot, which
 * holds the negated number of sequences encoded.  Four byte sequences
 * are decoded into two slots, holding the index of the final and penultimate
 * byte of the sequence respectively.  If the first three bytes are FOLLOW
 * bytes, we assume that there is a surrogate straddling the end of the
 * previous 8 bytes and these 8 bytes and start with a 4TAIL case.
 *
 * Here is a sample table entry: for input vector
 *
 *     40 C2 A7 E2 88 88 F0 9D 92 AA E2
 *
 * we get FOLLOW syndrome
 *
 *     00 00 FF 00 FF FF 00 FF(FF FF 00)
 *
 * followed by two additional FOLLOW bytes (subtable 2),
 * and Tetranacci index
 *
 *     4 + 15 + 29 + 108 = 156
 *
 * at which we find entry (table offset 0x4e0)
 *
 *     00 12 25 68 59 FF FF FB
 *
 * representing:
 *
 *     00: ASCII ending at index 0 (40)
 *     12: 2BYTE ending at index 2 (C2 A7)
 *     25: 3BYTE ending at index 5 (E2 88 88)
 *     68: 4HEAD ending at index 8 (F0 9D 92)
 *     59: 4TAIL ending at index 9 (92 AA)
 *     FF: EMPTY
 *     FF: EMPTY
 *     FB: EMPTY indicating -FB = 5 halfwords of output
 */

#include <assert.h>
#include <stdalign.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

enum { TABLEN = 208 };

static const int tablens[4] = { 208, 193, 164, 108 };

alignas(8) unsigned char utf8_to_utf16le_neon_tab[4][TABLEN][8];

static void
gentab(unsigned char tab[TABLEN][8], int suffix)
{
	long m, i;

	memset(tab, 0xff, TABLEN * sizeof *tab);

	for (m = i = 0; m <= 0xff; m ++) {
		int j, k, start;

		/* four or more consecutive bits set in m? */
		if (m & m >> 1 & m >> 2 & m >> 3)
			continue;

		j = 0; /* tab[i] */
		k = 0; /* iterates through m */

		/* special case: three initial follow bytes -> starts with 4TAIL */
		if ((m & 0x7) == 7)
			tab[i][j++] = 0x52;

		start = __builtin_ctz(~m); /* start of current sequence */

		/* iterate over bits of m, skipping the first bit */
		for (k = start + 1; k < 12; k++) {
			/* follow byte? */
			if ((m|suffix) & 1 << k)
				continue;

			/* else first byte of next sequence */
			switch (k - start) {
			case 1:	tab[i][j++] = k - 1;
				break;

			case 2:	tab[i][j++] = k - 1 | 0x10;
				break;

			case 3:	tab[i][j++] = k - 1 | 0x20;
				break;

			case 4:	tab[i][j++] = k - 2 | 0x60;

				/* special case: 4TAIL handled in next sequence */
				if (start == 7)
					goto done;

				tab[i][j++] = k - 1 | 0x50;
				break;

			default:
				/* suffix doesn't make sense with syndrome -- unused entry */
				if (k >= 8) {
					memset(tab[i], 0xff, sizeof tab[i]);
					goto continue_outer;
				} else
					assert(k - start <= 4);
			}

			start = k;

			if (start >= 8)
				goto done;

			assert(j < 8);
		}

		/* go to next table row */
	done:	if (j < 8)
			tab[i][7] = -j;

	continue_outer:
		i++;

	}

	assert(i == TABLEN);
}

int main()
{
	int t;
	long i, m;

	gentab(utf8_to_utf16le_neon_tab[0], 0x000);
	gentab(utf8_to_utf16le_neon_tab[1], 0x100);
	gentab(utf8_to_utf16le_neon_tab[2], 0x300);
	gentab(utf8_to_utf16le_neon_tab[3], 0x700);

	printf("/* --- GENERATED BY mktab_neon.c DO NOT EDIT --- */\n\n"
	    "#include <stdalign.h>\n\n"
	    "alignas(8) unsigned const char utf8_to_utf16le_neon_tab[%d][8] = {",
	    tablens[0] + tablens[1] + tablens[2] + tablens[3]);

	for (t = 0; t < 4; t++) {
		putchar('\n');

		for (m = i = 0; m <= 0xff; m ++) {
			int j;

			/* four or more consecutive bits set in m? */
			if (m & m >> 1 & m >> 2 & m >> 3)
				continue;

			/* skip unused rows */
			if (utf8_to_utf16le_neon_tab[t][i][0] == 0xff) {
				break;
			}

			fputs("\t{", stdout);

			for (j = 0; j < 8; j++)
				printf(" 0x%02x,", (unsigned)utf8_to_utf16le_neon_tab[t][i][j]);

			printf(" }, /* %01d/%02x */\n", t, (unsigned)m);
			i++;
		}

		assert(i == tablens[t]);
	}

	puts("};");


	if (ferror(stdout)) {
		perror("stdout");

		return (EXIT_FAILURE);
	}

	return (EXIT_SUCCESS);
}
