# CMake generated Testfile for 
# Source directory: /home/leorio/simdutf/tests
# Build directory: /home/leorio/simdutf/builds390/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(random_fuzzer "random_fuzzer")
set_tests_properties(random_fuzzer PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;13;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(special_tests "special_tests")
set_tests_properties(special_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;18;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_ascii_basic_tests "validate_ascii_basic_tests")
set_tests_properties(validate_ascii_basic_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;24;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_ascii_with_errors_tests "validate_ascii_with_errors_tests")
set_tests_properties(validate_ascii_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;29;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(bele_tests "bele_tests")
set_tests_properties(bele_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;34;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf8_basic_tests "validate_utf8_basic_tests")
set_tests_properties(validate_utf8_basic_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;39;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(select_implementation "select_implementation")
set_tests_properties(select_implementation PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;45;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf8_brute_force_tests "validate_utf8_brute_force_tests")
set_tests_properties(validate_utf8_brute_force_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;50;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf8_puzzler_tests "validate_utf8_puzzler_tests")
set_tests_properties(validate_utf8_puzzler_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;55;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf8_with_errors_tests "validate_utf8_with_errors_tests")
set_tests_properties(validate_utf8_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;61;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf16le_basic_tests "validate_utf16le_basic_tests")
set_tests_properties(validate_utf16le_basic_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;67;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf16be_basic_tests "validate_utf16be_basic_tests")
set_tests_properties(validate_utf16be_basic_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;73;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf16le_with_errors_tests "validate_utf16le_with_errors_tests")
set_tests_properties(validate_utf16le_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;79;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf16be_with_errors_tests "validate_utf16be_with_errors_tests")
set_tests_properties(validate_utf16be_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;85;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf32_basic_tests "validate_utf32_basic_tests")
set_tests_properties(validate_utf32_basic_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;91;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(validate_utf32_with_errors_tests "validate_utf32_with_errors_tests")
set_tests_properties(validate_utf32_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;97;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_latin1_to_utf8_tests "convert_latin1_to_utf8_tests")
set_tests_properties(convert_latin1_to_utf8_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;115;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_latin1_to_utf16le_tests "convert_latin1_to_utf16le_tests")
set_tests_properties(convert_latin1_to_utf16le_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;120;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_latin1_to_utf16be_tests "convert_latin1_to_utf16be_tests")
set_tests_properties(convert_latin1_to_utf16be_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;126;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_latin1_to_utf32_tests "convert_latin1_to_utf32_tests")
set_tests_properties(convert_latin1_to_utf32_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;132;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_latin1_tests "convert_utf8_to_latin1_tests")
set_tests_properties(convert_utf8_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;137;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_latin1_with_errors_tests "convert_utf8_to_latin1_with_errors_tests")
set_tests_properties(convert_utf8_to_latin1_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;142;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf8_to_latin1_tests "convert_valid_utf8_to_latin1_tests")
set_tests_properties(convert_valid_utf8_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;147;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf8_to_utf16le_tests "convert_valid_utf8_to_utf16le_tests")
set_tests_properties(convert_valid_utf8_to_utf16le_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;152;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf8_to_utf16be_tests "convert_valid_utf8_to_utf16be_tests")
set_tests_properties(convert_valid_utf8_to_utf16be_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;158;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf8_to_utf32_tests "convert_valid_utf8_to_utf32_tests")
set_tests_properties(convert_valid_utf8_to_utf32_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;164;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_utf16le_tests "convert_utf8_to_utf16le_tests")
set_tests_properties(convert_utf8_to_utf16le_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;170;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_utf16be_tests "convert_utf8_to_utf16be_tests")
set_tests_properties(convert_utf8_to_utf16be_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;176;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_utf16le_with_errors_tests "convert_utf8_to_utf16le_with_errors_tests")
set_tests_properties(convert_utf8_to_utf16le_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;182;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_utf16be_with_errors_tests "convert_utf8_to_utf16be_with_errors_tests")
set_tests_properties(convert_utf8_to_utf16be_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;188;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_utf32_tests "convert_utf8_to_utf32_tests")
set_tests_properties(convert_utf8_to_utf32_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;194;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf8_to_utf32_with_errors_tests "convert_utf8_to_utf32_with_errors_tests")
set_tests_properties(convert_utf8_to_utf32_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;200;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16le_to_latin1_tests "convert_utf16le_to_latin1_tests")
set_tests_properties(convert_utf16le_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;206;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16be_to_latin1_tests "convert_utf16be_to_latin1_tests")
set_tests_properties(convert_utf16be_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;211;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16le_to_latin1_tests_with_errors "convert_utf16le_to_latin1_tests_with_errors")
set_tests_properties(convert_utf16le_to_latin1_tests_with_errors PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;216;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16be_to_latin1_tests_with_errors "convert_utf16be_to_latin1_tests_with_errors")
set_tests_properties(convert_utf16be_to_latin1_tests_with_errors PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;221;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf16le_to_latin1_tests "convert_valid_utf16le_to_latin1_tests")
set_tests_properties(convert_valid_utf16le_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;226;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf16be_to_latin1_tests "convert_valid_utf16be_to_latin1_tests")
set_tests_properties(convert_valid_utf16be_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;231;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16le_to_utf8_tests "convert_utf16le_to_utf8_tests")
set_tests_properties(convert_utf16le_to_utf8_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;236;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16be_to_utf8_tests "convert_utf16be_to_utf8_tests")
set_tests_properties(convert_utf16be_to_utf8_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;242;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16le_to_utf8_with_errors_tests "convert_utf16le_to_utf8_with_errors_tests")
set_tests_properties(convert_utf16le_to_utf8_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;248;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16be_to_utf8_with_errors_tests "convert_utf16be_to_utf8_with_errors_tests")
set_tests_properties(convert_utf16be_to_utf8_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;254;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_latin1_tests "convert_utf32_to_latin1_tests")
set_tests_properties(convert_utf32_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;260;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf32_to_latin1_tests "convert_valid_utf32_to_latin1_tests")
set_tests_properties(convert_valid_utf32_to_latin1_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;265;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_latin1_with_errors_tests "convert_utf32_to_latin1_with_errors_tests")
set_tests_properties(convert_utf32_to_latin1_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;270;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_utf8_tests "convert_utf32_to_utf8_tests")
set_tests_properties(convert_utf32_to_utf8_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;275;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_utf8_with_errors_tests "convert_utf32_to_utf8_with_errors_tests")
set_tests_properties(convert_utf32_to_utf8_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;281;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_utf16le_tests "convert_utf32_to_utf16le_tests")
set_tests_properties(convert_utf32_to_utf16le_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;287;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_utf16be_tests "convert_utf32_to_utf16be_tests")
set_tests_properties(convert_utf32_to_utf16be_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;293;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_utf16le_with_errors_tests "convert_utf32_to_utf16le_with_errors_tests")
set_tests_properties(convert_utf32_to_utf16le_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;299;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf32_to_utf16be_with_errors_tests "convert_utf32_to_utf16be_with_errors_tests")
set_tests_properties(convert_utf32_to_utf16be_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;305;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf16le_to_utf8_tests "convert_valid_utf16le_to_utf8_tests")
set_tests_properties(convert_valid_utf16le_to_utf8_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;311;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf16be_to_utf8_tests "convert_valid_utf16be_to_utf8_tests")
set_tests_properties(convert_valid_utf16be_to_utf8_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;317;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf32_to_utf8_tests "convert_valid_utf32_to_utf8_tests")
set_tests_properties(convert_valid_utf32_to_utf8_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;323;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf32_to_utf16le_tests "convert_valid_utf32_to_utf16le_tests")
set_tests_properties(convert_valid_utf32_to_utf16le_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;329;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf32_to_utf16be_tests "convert_valid_utf32_to_utf16be_tests")
set_tests_properties(convert_valid_utf32_to_utf16be_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;335;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16le_to_utf32_tests "convert_utf16le_to_utf32_tests")
set_tests_properties(convert_utf16le_to_utf32_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;341;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16be_to_utf32_tests "convert_utf16be_to_utf32_tests")
set_tests_properties(convert_utf16be_to_utf32_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;347;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16le_to_utf32_with_errors_tests "convert_utf16le_to_utf32_with_errors_tests")
set_tests_properties(convert_utf16le_to_utf32_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;353;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_utf16be_to_utf32_with_errors_tests "convert_utf16be_to_utf32_with_errors_tests")
set_tests_properties(convert_utf16be_to_utf32_with_errors_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;359;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf16le_to_utf32_tests "convert_valid_utf16le_to_utf32_tests")
set_tests_properties(convert_valid_utf16le_to_utf32_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;365;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(convert_valid_utf16be_to_utf32_tests "convert_valid_utf16be_to_utf32_tests")
set_tests_properties(convert_valid_utf16be_to_utf32_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;371;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(count_utf8 "count_utf8")
set_tests_properties(count_utf8 PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;377;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(count_utf16le "count_utf16le")
set_tests_properties(count_utf16le PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;383;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(count_utf16be "count_utf16be")
set_tests_properties(count_utf16be PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;389;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(detect_encodings_tests "detect_encodings_tests")
set_tests_properties(detect_encodings_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;395;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
add_test(basic_fuzzer "basic_fuzzer")
set_tests_properties(basic_fuzzer PROPERTIES  _BACKTRACE_TRIPLES "/home/leorio/simdutf/cmake/add_cpp_test.cmake;33;add_test;/home/leorio/simdutf/tests/CMakeLists.txt;401;add_cpp_test;/home/leorio/simdutf/tests/CMakeLists.txt;0;")
subdirs("helpers")
subdirs("reference")
