#!/usr/bin/env python3

# Parses NormalizationTest.txt (from the Unicode Character Database) and
# generates a C++ header defining an array of test cases, for use by
# tests/normalization_test.cpp.

from dataclasses import dataclass
from pathlib import Path
import unicodedata

SCRIPT_DIR = Path(__file__).resolve().parent
INPUT_FILE = SCRIPT_DIR / "NormalizationTest.txt"
OUTPUT_FILE = SCRIPT_DIR / "normalization_test_data.h"


@dataclass
class TestCase:
    c1: str
    c2: str
    c3: str
    c4: str
    c5: str
    line: int


def escape_byte(b: int) -> str:
    if b == ord("\\"):
        return "\\\\"
    if b == ord('"'):
        return '\\"'
    if 0x20 <= b < 0x7F:
        return chr(b)
    # Octal escapes are always exactly 3 digits so that they can't
    # accidentally swallow a following digit character.
    return "\\{:03o}".format(b)


def parse_unicode_string(s: str) -> str:
    code_points = [int(c, base=16) for c in s.split()]
    text = "".join(chr(c) for c in code_points)
    return "".join(escape_byte(b) for b in text.encode("utf-8"))


def parse_test_cases() -> list[TestCase]:
    test_cases: list[TestCase] = []
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        for i, line in enumerate(f.readlines()):
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("@"):
                continue
            # Each line ends with a trailing ';', so drop the empty field it
            # produces.
            parts = [p.strip() for p in line.split(";") if p.strip()]
            if len(parts) != 5:
                continue
            str_parts = [parse_unicode_string(p) for p in parts]
            test_case = TestCase(*str_parts, i + 1)
            test_cases.append(test_case)
    return test_cases


def write_header(test_cases: list[TestCase]) -> None:
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(
            "// This file was generated by tests/normalization_test_data/generate.py\n"
        )
        f.write(
            "// It is derived from NormalizationTest.txt, part of the Unicode Character\n"
        )
        f.write("// Database. Do not edit it by hand.\n")
        f.write("#ifndef SIMDUTF_NORMALIZATION_TEST_DATA_H\n")
        f.write("#define SIMDUTF_NORMALIZATION_TEST_DATA_H\n\n")
        f.write("#include <array>\n#include <string>\n\n")
        f.write("using namespace std::literals;\n")
        f.write("namespace simdutf {\n")
        f.write("namespace test {\n\n")
        f.write("struct NormalizationTestCase {\n")
        f.write("  std::string_view c1;\n")
        f.write("  std::string_view c2;\n")
        f.write("  std::string_view c3;\n")
        f.write("  std::string_view c4;\n")
        f.write("  std::string_view c5;\n")
        f.write("  size_t line;\n")
        f.write("  bool no_repeat;\n")
        f.write("};\n\n")
        f.write(
            "const std::array<NormalizationTestCase, {}> "
            "normalization_test_cases{{{{\n".format(len(test_cases))
        )
        for tc in test_cases:
            f.write(
                '    {{"{}"sv, "{}"sv, "{}"sv, "{}"sv, "{}"sv, {}}},\n'.format(
                    tc.c1,
                    tc.c2,
                    tc.c3,
                    tc.c4,
                    tc.c5,
                    tc.line,
                )
            )
        f.write("}};\n\n")
        f.write("} // namespace test\n")
        f.write("} // namespace simdutf\n\n")
        f.write("#endif // SIMDUTF_NORMALIZATION_TEST_DATA_H\n")


def main() -> None:
    test_cases = parse_test_cases()
    write_header(test_cases)
    print(f"Generated {len(test_cases)} test cases -> {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
