#!/usr/bin/env python3
"""Post-process MrDocs HTML output: build the sidebar nav tree + search index.

MrDocs' html generator emits no navigation. This reads the tagfile it does
emit (reference.tag.xml) and writes a single mrdocs-nav.js into the output
directory. The wrapper template (mrdocs-addons/.../wrapper.html.hbs) already
references it via <script src> and provides the #nav-tree / #nav-search hooks.

Run after `mrdocs mrdocs.yml`:  python3 scripts/mrdocs_nav.py
"""
import json
import pathlib
import xml.etree.ElementTree as ET

OUT_DIR = pathlib.Path("doc/mrdocs-html")
TAGFILE = OUT_DIR / "reference.tag.xml"

# Namespaces to omit from the sidebar/search. simdutf::detail and
# simdutf::internal are tagged implementation-defined in mrdocs.yml (they leak
# into public signatures), so they stay in the corpus -- references to them
# resolve -- but they are not public API, so we drop them from navigation.
# simdutf::tables is fully excluded but listed defensively in case a dependency
# pulls a stray compound into the tagfile.
EXCLUDE_NS_PREFIXES = ("simdutf::detail", "simdutf::internal", "simdutf::tables")


def is_excluded(qual):
    return any(qual == p or qual.startswith(p + "::") for p in EXCLUDE_NS_PREFIXES)


def build_index():
    root = ET.parse(TAGFILE).getroot()

    # filename for every compound (namespace/class/struct/enum), keyed by name
    compound_file = {}
    for c in root.findall("compound"):
        name = c.findtext("name")
        fn = c.findtext("filename")
        if name and fn:
            compound_file[name] = fn

    namespaces = []
    search = []
    for c in root.findall("compound"):
        if c.get("kind") != "namespace":
            continue
        ns_name = c.findtext("name")
        if ns_name and is_excluded(ns_name):
            continue
        ns_file = c.findtext("filename")
        classes, functions = [], []
        for cls in c.findall("class"):
            cn = (cls.text or "").strip()
            short = cn.split("::")[-1]
            url = compound_file.get(cn)
            if url and not is_excluded(cn):
                classes.append({"name": short, "qual": cn, "url": url})
                search.append({"name": short, "qual": cn, "url": url, "kind": "type"})
        for m in c.findall("member"):
            if m.get("kind") != "function":
                continue
            mn = m.findtext("name")
            url = m.findtext("anchorfile")
            args = (m.findtext("arglist") or "").strip()
            if mn and url:
                qual = f"{ns_name}::{mn}" if ns_name else mn
                functions.append({"name": mn, "qual": qual, "url": url, "args": args})
                search.append({"name": mn, "qual": qual, "url": url, "kind": "func"})
        if not classes and not functions:
            continue  # skip empty namespaces (e.g. fully excluded ones)
        classes.sort(key=lambda x: x["name"].lower())
        functions.sort(key=lambda x: x["name"].lower())
        namespaces.append({
            "name": ns_name or "(global namespace)",
            "url": ns_file,
            "classes": classes,
            "functions": functions,
        })
    namespaces.sort(key=lambda x: x["name"].lower())
    search.sort(key=lambda x: x["name"].lower())
    return namespaces, search


JS_TEMPLATE = r"""// Generated by scripts/mrdocs_nav.py — sidebar nav tree + client-side search.
(function () {
  var NAV = __NAV__;
  var SEARCH = __SEARCH__;
  // Derive the relative path to the output root from this script's own src
  // (e.g. "./mrdocs-nav.js" at root, "../mrdocs-nav.js" one level deep).
  var self = document.querySelector('script[src$="mrdocs-nav.js"]');
  var ROOT = self ? self.getAttribute('src').replace(/mrdocs-nav\.js$/, '') : './';
  var here = decodeURIComponent(location.pathname);

  function el(tag, attrs, children) {
    var e = document.createElement(tag);
    if (attrs) for (var k in attrs) {
      if (k === 'class') e.className = attrs[k];
      else if (k === 'text') e.textContent = attrs[k];
      else e.setAttribute(k, attrs[k]);
    }
    (children || []).forEach(function (c) { e.appendChild(c); });
    return e;
  }
  function link(entry) {
    var a = el('a', { href: ROOT + entry.url, title: entry.qual || entry.name });
    a.textContent = entry.name;
    if (here.length >= entry.url.length && here.slice(-entry.url.length) === entry.url) {
      a.className = 'current';
    }
    return a;
  }
  function list(items) {
    var ul = el('ul');
    items.forEach(function (it) { ul.appendChild(el('li', null, [link(it)])); });
    return ul;
  }

  var tree = document.getElementById('nav-tree');
  if (tree) {
    NAV.forEach(function (ns) {
      var det = el('details', {});
      det.open = true;
      det.appendChild(el('summary', { text: ns.name + (ns.url ? '' : '') }));
      if (ns.functions.length) {
        det.appendChild(el('div', { class: 'group-label', text: 'Functions' }));
        det.appendChild(list(ns.functions));
      }
      if (ns.classes.length) {
        det.appendChild(el('div', { class: 'group-label', text: 'Types' }));
        det.appendChild(list(ns.classes));
      }
      tree.appendChild(det);
    });
    // make the namespace summary itself a link target
    var firstCurrent = tree.querySelector('a.current');
    if (firstCurrent) firstCurrent.scrollIntoView({ block: 'center' });
  }

  // ---- search ----
  var box = document.getElementById('nav-search');
  if (box && tree) {
    var results = el('ul', { id: 'search-results', class: '' });
    var empty = el('div', { id: 'search-empty', text: 'No matches' });
    results.style.display = 'none';
    empty.style.display = 'none';
    var groups = [];
    box.addEventListener('input', function () {
      var q = box.value.trim().toLowerCase();
      if (!groups.length) {
        // lazily detach the tree's detail groups so we can show/hide
        groups = Array.prototype.slice.call(tree.children);
        tree.appendChild(empty);
        tree.appendChild(results);
      }
      if (!q) {
        groups.forEach(function (g) { g.style.display = ''; });
        results.style.display = 'none'; empty.style.display = 'none';
        return;
      }
      groups.forEach(function (g) { g.style.display = 'none'; });
      var matches = SEARCH.filter(function (s) {
        return s.name.toLowerCase().indexOf(q) !== -1 ||
               s.qual.toLowerCase().indexOf(q) !== -1;
      }).slice(0, 60);
      results.innerHTML = '';
      matches.forEach(function (m) {
        var a = el('a', { href: ROOT + m.url, title: m.qual });
        a.appendChild(el('span', { text: m.name }));
        var ns = m.qual.indexOf('::') !== -1 ? m.qual.slice(0, m.qual.lastIndexOf('::')) : '';
        if (ns) a.appendChild(el('span', { class: 'qual', text: '  ' + ns }));
        results.appendChild(el('li', null, [a]));
      });
      results.style.display = matches.length ? '' : 'none';
      empty.style.display = matches.length ? 'none' : '';
    });
  }
})();
"""


def main():
    namespaces, search = build_index()
    js = (JS_TEMPLATE
          .replace("__NAV__", json.dumps(namespaces, ensure_ascii=False))
          .replace("__SEARCH__", json.dumps(search, ensure_ascii=False)))
    (OUT_DIR / "mrdocs-nav.js").write_text(js, encoding="utf-8")
    nfunc = sum(len(n["functions"]) for n in namespaces)
    ntype = sum(len(n["classes"]) for n in namespaces)
    print(f"mrdocs-nav.js: {len(namespaces)} namespaces, {ntype} types, "
          f"{nfunc} functions, {len(search)} search entries")


if __name__ == "__main__":
    main()
