name: Ubuntu ppc64le (GCC 13)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v3
        name: Test
        id: runcmd
        with:
          arch: ppc64le
          githubToken: ${{ github.token }}
          distro: ubuntu22.04
          install: |
            apt-get update -q -y
            apt-get install -y cmake make g++
          run: |
            cmake -DCMAKE_BUILD_TYPE=Release -B build
            cmake --build build
            ctest --output-on-failure --test-dir build
