name: Ubuntu 20.04 CI (GCC 9)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Use cmake with address sanitizer
        run: |
          mkdir build &&
          cd build &&
          cmake -DSIMDUTF_SANITIZE=ON ..  &&
          cmake --build .   &&
          ctest -j --output-on-failure
      - name: Use cmake with undefined behavior sanitizer
        run: |
          mkdir buildundef &&
          cd buildundef &&
          cmake -DSIMDUTF_SANITIZE_UNDEFINED=ON ..  &&
          cmake --build .   &&
          ctest -j --output-on-failure