name: Ubuntu 18.04 CI (GCC 7)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          cmake -DCMAKE_CXX_FLAGS=-Werror ..  -DSIMDUTF_BENCHMARKS=OFF  -DSIMDUTF_BENCHMARKS=OFF &&
          cmake --build .  --verbose &&
          ctest -j --output-on-failure
