name: Ubuntu 20.04 C++11 (GCC 9)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          cmake -DCMAKE_CXX_FLAGS=-Werror -DSIMDUTF_ALWAYS_INCLUDE_FALLBACK=ON -DCMAKE_INSTALL_PREFIX:PATH=destination -DCMAKE_CXX_STANDARD=11 -DSIMDUTF_BENCHMARKS=OFF .. &&
          cmake --build .   &&
          ctest -j --output-on-failure &&
          cmake --install . &&
          cd ../tests/installation_tests/find &&
          mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=../../../build/destination .. &&  cmake --build .
